apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u4k4bm09i-dotnet-basic
  janus-idp.io/tekton: u4k4bm09i-dotnet-basic
  backstage.io/kubernetes-id: u4k4bm09i-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u4k4bm09i-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
